[tool.poetry]
name = "aladdin"
version = "0.1.0"
description = ""
authors = ["Fivestars <dev@fivestars.com>"]

[tool.poetry.dependencies]
python = "^3.7"
awscli = "1.18.62"
boto3 = "1.13.12"
cached-property = "1.5.1"
colorlog = "4.1.0"
jmespath = "0.10.0"
kubernetes = "11.0.0b2"
build-components = {path = "build-components"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
