[tool.poetry]
name = "aladdin"
version = "1.19.7.4"
description = ""
authors = ["Fivestars <dev@fivestars.com>"]
include = [
    "aladdin.sh",
    "aladdin-container.sh",
    "scripts/*",
]
repository = "https://github.com/fivestars-os/aladdin"
homepage = "https://github.com/fivestars-os/aladdin"

[tool.poetry.dependencies]
python = "^3.7"
awscli = "1.18.175"
boto3 = "1.16.15"
cached-property = "1.5.1"
jmespath = "0.10.0"
kubernetes = "12.0.01"
orderedset = "^2.0.3"
coloredlogs = "^14.0"
verboselogs = "^1.7"
PyYAML = "^5.3.1"
networkx = "^2.4"
jinja2 = "^2.11.2"
lazy-object-proxy = "^1.5.1"
urllib3 = "1.25.11"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
aladdin = "aladdin.main:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
